### ISSUE TITLE
troubles with make and make install

### ISSUE THREAD

**Issue by natanael87** [psi-squared/libSU3#1]
I can't use this library because of error in command make.
This is what appeared me when I write "make"
`eliasnto@dell-elias ~/Packages/libSU3-1.0 $ make
CC src/isoscalars.cc
In file included from include/SU3.h:7:0,
                 from src/SU3_internal.h:6,
                 from src/isoscalars.cc:9:
/usr/include/gmpxx.h:436:45: error: ‘mp_bitcnt_t’ has not been declared
   static void eval(mpz_ptr z, mpz_srcptr w, mp_bitcnt_t l)
                                             ^
/usr/include/gmpxx.h:445:45: error: ‘mp_bitcnt_t’ has not been declared
   static void eval(mpq_ptr q, mpq_srcptr r, mp_bitcnt_t l)
                                             ^
/usr/include/gmpxx.h:454:45: error: ‘mp_bitcnt_t’ has not been declared
   static void eval(mpf_ptr f, mpf_srcptr g, mp_bitcnt_t l)
                                             ^
/usr/include/gmpxx.h:460:45: error: ‘mp_bitcnt_t’ has not been declared
   static void eval(mpz_ptr z, mpz_srcptr w, mp_bitcnt_t l)
                                             ^
/usr/include/gmpxx.h:469:45: error: ‘mp_bitcnt_t’ has not been declared
   static void eval(mpq_ptr q, mpq_srcptr r, mp_bitcnt_t l)
                                             ^
/usr/include/gmpxx.h:478:45: error: ‘mp_bitcnt_t’ has not been declared
   static void eval(mpf_ptr f, mpf_srcptr g, mp_bitcnt_t l)
                                             ^
/usr/include/gmpxx.h:1110:50: error: ‘mp_bitcnt_t’ has not been declared
   static void eval(mpz_ptr z, gmp_randstate_t s, mp_bitcnt_t l)
                                                  ^
/usr/include/gmpxx.h:1114:50: error: ‘mp_bitcnt_t’ has not been declared
   static void eval(mpf_ptr f, gmp_randstate_t s, mp_bitcnt_t prec)
                                                  ^
/usr/include/gmpxx.h:1406:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const { return mpf_get_default_prec(); }
   ^
/usr/include/gmpxx.h:1522:3: error: declaration of ‘operator<<=’ as non-function
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator<<=)
   ^
/usr/include/gmpxx.h:1522:3: error: expected ‘;’ at end of member declaration
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator<<=)
   ^
/usr/include/gmpxx.h:1523:3: error: declaration of ‘operator>>=’ as non-function
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator>>=)
   ^
/usr/include/gmpxx.h:1523:3: error: expected ‘;’ at end of member declaration
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator>>=)
   ^
/usr/include/gmpxx.h:1523:3: error: redeclaration of ‘int __gmp_expr<__mpz_struct [1], __mpz_struct [1]>::mp_bitcnt_t’
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator>>=)
   ^
/usr/include/gmpxx.h:1522:3: note: previous declaration ‘int __gmp_expr<__mpz_struct [1], __mpz_struct [1]>::mp_bitcnt_t’
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator<<=)
   ^
/usr/include/gmpxx.h:1557:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const { return mpf_get_default_prec(); }
   ^
/usr/include/gmpxx.h:1700:3: error: declaration of ‘operator<<=’ as non-function
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator<<=)
   ^
/usr/include/gmpxx.h:1700:3: error: expected ‘;’ at end of member declaration
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator<<=)
   ^
/usr/include/gmpxx.h:1701:3: error: declaration of ‘operator>>=’ as non-function
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator>>=)
   ^
/usr/include/gmpxx.h:1701:3: error: expected ‘;’ at end of member declaration
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator>>=)
   ^
/usr/include/gmpxx.h:1701:3: error: redeclaration of ‘int __gmp_expr<__mpq_struct [1], __mpq_struct [1]>::mp_bitcnt_t’
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator>>=)
   ^
/usr/include/gmpxx.h:1700:3: note: previous declaration ‘int __gmp_expr<__mpq_struct [1], __mpq_struct [1]>::mp_bitcnt_t’
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator<<=)
   ^
/usr/include/gmpxx.h:1747:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const { return mpf_get_prec(mp); }
   ^
/usr/include/gmpxx.h:1749:17: error: ‘mp_bitcnt_t’ has not been declared
   void set_prec(mp_bitcnt_t prec) { mpf_set_prec(mp, prec); }
                 ^
/usr/include/gmpxx.h:1750:21: error: ‘mp_bitcnt_t’ has not been declared
   void set_prec_raw(mp_bitcnt_t prec) { mpf_set_prec_raw(mp, prec); }
                     ^
/usr/include/gmpxx.h:1761:35: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(const __gmp_expr &f, mp_bitcnt_t prec)
                                   ^
/usr/include/gmpxx.h:1767:44: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(const __gmp_expr<T, U> &expr, mp_bitcnt_t prec)
                                            ^
/usr/include/gmpxx.h:1772:29: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(signed char c, mp_bitcnt_t prec)
                             ^
/usr/include/gmpxx.h:1774:31: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(unsigned char c, mp_bitcnt_t prec)
                               ^
/usr/include/gmpxx.h:1777:28: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(signed int i, mp_bitcnt_t prec)
                            ^
/usr/include/gmpxx.h:1779:30: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(unsigned int i, mp_bitcnt_t prec)
                              ^
/usr/include/gmpxx.h:1782:34: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(signed short int s, mp_bitcnt_t prec)
                                  ^
/usr/include/gmpxx.h:1784:36: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(unsigned short int s, mp_bitcnt_t prec)
                                    ^
/usr/include/gmpxx.h:1787:33: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(signed long int l, mp_bitcnt_t prec)
                                 ^
/usr/include/gmpxx.h:1789:35: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(unsigned long int l, mp_bitcnt_t prec)
                                   ^
/usr/include/gmpxx.h:1792:23: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(float f, mp_bitcnt_t prec)
                       ^
/usr/include/gmpxx.h:1794:24: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(double d, mp_bitcnt_t prec)
                        ^
/usr/include/gmpxx.h:1808:29: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(const char *s, mp_bitcnt_t prec, int base = 0)
                             ^
/usr/include/gmpxx.h:1825:36: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(const std::string &s, mp_bitcnt_t prec, int base = 0)
                                    ^
/usr/include/gmpxx.h:1837:28: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(mpf_srcptr f, mp_bitcnt_t prec)
                            ^
/usr/include/gmpxx.h:1913:3: error: declaration of ‘operator<<=’ as non-function
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator<<=)
   ^
/usr/include/gmpxx.h:1913:3: error: expected ‘;’ at end of member declaration
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator<<=)
   ^
/usr/include/gmpxx.h:1914:3: error: declaration of ‘operator>>=’ as non-function
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator>>=)
   ^
/usr/include/gmpxx.h:1914:3: error: expected ‘;’ at end of member declaration
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator>>=)
   ^
/usr/include/gmpxx.h:1914:3: error: redeclaration of ‘int __gmp_expr<__mpf_struct [1], __mpf_struct [1]>::mp_bitcnt_t’
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator>>=)
   ^
/usr/include/gmpxx.h:1913:3: note: previous declaration ‘int __gmp_expr<__mpf_struct [1], __mpf_struct [1]>::mp_bitcnt_t’
   __GMP_DECLARE_COMPOUND_OPERATOR_UI(operator<<=)
   ^
/usr/include/gmpxx.h: In copy constructor ‘__gmp_expr<__mpf_struct [1], __mpf_struct [1]>::__gmp_expr(const __gmp_expr<__mpf_struct [1], __mpf_struct [1]>&)’:
/usr/include/gmpxx.h:1756:21: error: ‘const class __gmp_expr<__mpf_struct [1], __mpf_struct [1]>’ has no member named ‘get_prec’
   { mpf_init2(mp, f.get_prec()); mpf_set(mp, f.mp); }
                     ^
/usr/include/gmpxx.h: In constructor ‘__gmp_expr<__mpf_struct [1], __mpf_struct [1]>::__gmp_expr(__gmp_expr<__mpf_struct [1], __mpf_struct [1]>&&)’:
/usr/include/gmpxx.h:1759:43: error: ‘get_prec’ was not declared in this scope
   { *mp = *f.mp; mpf_init2(f.mp, get_prec()); }
                                           ^
/usr/include/gmpxx.h: At global scope:
/usr/include/gmpxx.h:2111:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const { return expr.val.get_prec(); }
   ^
/usr/include/gmpxx.h:2129:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const { return expr.val.get_prec(); }
   ^
/usr/include/gmpxx.h:2161:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const
   ^
/usr/include/gmpxx.h:2187:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const { return expr.val1.get_prec(); }
   ^
/usr/include/gmpxx.h:2205:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const { return expr.val2.get_prec(); }
   ^
/usr/include/gmpxx.h:2238:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const
   ^
/usr/include/gmpxx.h:2273:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const
   ^
/usr/include/gmpxx.h:2308:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const
   ^
/usr/include/gmpxx.h:2343:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const
   ^
/usr/include/gmpxx.h:2372:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const { return expr.val1.get_prec(); }
   ^
/usr/include/gmpxx.h:2393:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const { return expr.val2.get_prec(); }
   ^
/usr/include/gmpxx.h:2419:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const
   ^
/usr/include/gmpxx.h:2447:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const
   ^
/usr/include/gmpxx.h:2475:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const
   ^
/usr/include/gmpxx.h:2664:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_plus)
 ^
/usr/include/gmpxx.h:2664:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_plus)
 ^
/usr/include/gmpxx.h:2664:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_plus)
 ^
/usr/include/gmpxx.h:2664:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_plus)
 ^
/usr/include/gmpxx.h:2664:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_plus)
 ^
/usr/include/gmpxx.h:2664:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_plus)
 ^
/usr/include/gmpxx.h:2664:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_plus)
 ^
/usr/include/gmpxx.h:2664:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_plus)
 ^
/usr/include/gmpxx.h:2665:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_minus)
 ^
/usr/include/gmpxx.h:2665:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_minus)
 ^
/usr/include/gmpxx.h:2665:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_minus)
 ^
/usr/include/gmpxx.h:2665:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_minus)
 ^
/usr/include/gmpxx.h:2665:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_minus)
 ^
/usr/include/gmpxx.h:2665:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_minus)
 ^
/usr/include/gmpxx.h:2665:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_minus)
 ^
/usr/include/gmpxx.h:2665:1: error: ‘mp_bitcnt_t’ does not name a type
 __GMPZQ_DEFINE_EXPR(__gmp_binary_minus)
 ^
/usr/include/gmpxx.h:2971:1: error: ‘mp_bitcnt_t’ was not declared in this scope
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator<<, __gmp_binary_lshift)
 ^
/usr/include/gmpxx.h:2971:1: error: template argument 2 is invalid
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator<<, __gmp_binary_lshift)
 ^
/usr/include/gmpxx.h:2971:1: error: template argument 2 is invalid
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator<<, __gmp_binary_lshift)
 ^
/usr/include/gmpxx.h:2971:1: error: ‘mp_bitcnt_t’ has not been declared
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator<<, __gmp_binary_lshift)
 ^
/usr/include/gmpxx.h: In function ‘int operator<<(const __gmp_expr<T, U>&, int)’:
/usr/include/gmpxx.h:2971:1: error: ‘mp_bitcnt_t’ was not declared in this scope
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator<<, __gmp_binary_lshift)
 ^
/usr/include/gmpxx.h:2971:1: error: template argument 2 is invalid
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator<<, __gmp_binary_lshift)
 ^
/usr/include/gmpxx.h:2971:1: error: template argument 2 is invalid
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator<<, __gmp_binary_lshift)
 ^
/usr/include/gmpxx.h: At global scope:
/usr/include/gmpxx.h:2972:1: error: ‘mp_bitcnt_t’ was not declared in this scope
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator>>, __gmp_binary_rshift)
 ^
/usr/include/gmpxx.h:2972:1: error: template argument 2 is invalid
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator>>, __gmp_binary_rshift)
 ^
/usr/include/gmpxx.h:2972:1: error: template argument 2 is invalid
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator>>, __gmp_binary_rshift)
 ^
/usr/include/gmpxx.h:2972:1: error: ‘mp_bitcnt_t’ has not been declared
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator>>, __gmp_binary_rshift)
 ^
/usr/include/gmpxx.h: In function ‘int operator>>(const __gmp_expr<T, U>&, int)’:
/usr/include/gmpxx.h:2972:1: error: ‘mp_bitcnt_t’ was not declared in this scope
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator>>, __gmp_binary_rshift)
 ^
/usr/include/gmpxx.h:2972:1: error: template argument 2 is invalid
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator>>, __gmp_binary_rshift)
 ^
/usr/include/gmpxx.h:2972:1: error: template argument 2 is invalid
 __GMP_DEFINE_BINARY_FUNCTION_UI(operator>>, __gmp_binary_rshift)
 ^
/usr/include/gmpxx.h: At global scope:
/usr/include/gmpxx.h:3007:1: error: declaration of ‘operator<<=’ as non-function
 __GMPZ_DEFINE_COMPOUND_OPERATOR_UI(operator<<=, __gmp_binary_lshift)
 ^
/usr/include/gmpxx.h:3007:1: error: ‘mp_bitcnt_t’ was not declared in this scope
/usr/include/gmpxx.h:3008:1: error: declaration of ‘operator>>=’ as non-function
 __GMPZ_DEFINE_COMPOUND_OPERATOR_UI(operator>>=, __gmp_binary_rshift)
 ^
/usr/include/gmpxx.h:3008:1: error: ‘mp_bitcnt_t’ was not declared in this scope
/usr/include/gmpxx.h:3020:1: error: declaration of ‘operator<<=’ as non-function
 __GMPQ_DEFINE_COMPOUND_OPERATOR_UI(operator<<=, __gmp_binary_lshift)
 ^
/usr/include/gmpxx.h:3020:1: error: ‘mp_bitcnt_t’ was not declared in this scope
/usr/include/gmpxx.h:3021:1: error: declaration of ‘operator>>=’ as non-function
 __GMPQ_DEFINE_COMPOUND_OPERATOR_UI(operator>>=, __gmp_binary_rshift)
 ^
/usr/include/gmpxx.h:3021:1: error: ‘mp_bitcnt_t’ was not declared in this scope
/usr/include/gmpxx.h:3033:1: error: declaration of ‘operator<<=’ as non-function
 __GMPF_DEFINE_COMPOUND_OPERATOR_UI(operator<<=, __gmp_binary_lshift)
 ^
/usr/include/gmpxx.h:3033:1: error: ‘mp_bitcnt_t’ was not declared in this scope
/usr/include/gmpxx.h:3034:1: error: declaration of ‘operator>>=’ as non-function
 __GMPF_DEFINE_COMPOUND_OPERATOR_UI(operator>>=, __gmp_binary_rshift)
 ^
/usr/include/gmpxx.h:3034:1: error: ‘mp_bitcnt_t’ was not declared in this scope
/usr/include/gmpxx.h:3051:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t bits;
   ^
/usr/include/gmpxx.h:3053:33: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(gmp_randstate_t s, mp_bitcnt_t l) : state(s), bits(l) { }
                                 ^
/usr/include/gmpxx.h:3055:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const { return mpf_get_default_prec(); }
   ^
/usr/include/gmpxx.h: In constructor ‘__gmp_expr<__mpz_struct [1], __gmp_urandomb_value>::__gmp_expr(__gmp_randstate_struct*, int)’:
/usr/include/gmpxx.h:3053:60: error: class ‘__gmp_expr<__mpz_struct [1], __gmp_urandomb_value>’ does not have any field named ‘bits’
   __gmp_expr(gmp_randstate_t s, mp_bitcnt_t l) : state(s), bits(l) { }
                                                            ^
/usr/include/gmpxx.h: In member function ‘void __gmp_expr<__mpz_struct [1], __gmp_urandomb_value>::eval(mpz_ptr) const’:
/usr/include/gmpxx.h:3054:68: error: ‘bits’ was not declared in this scope
   void eval(mpz_ptr z) const { __gmp_rand_function::eval(z, state, bits); }
                                                                    ^
/usr/include/gmpxx.h: At global scope:
/usr/include/gmpxx.h:3068:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const { return mpf_get_default_prec(); }
   ^
/usr/include/gmpxx.h:3076:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t bits;
   ^
/usr/include/gmpxx.h:3078:33: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr(gmp_randstate_t s, mp_bitcnt_t l) : state(s), bits(l) { }
                                 ^
/usr/include/gmpxx.h:3084:3: error: ‘mp_bitcnt_t’ does not name a type
   mp_bitcnt_t get_prec() const
   ^
/usr/include/gmpxx.h: In constructor ‘__gmp_expr<__mpf_struct [1], __gmp_urandomb_value>::__gmp_expr(__gmp_randstate_struct*, int)’:
/usr/include/gmpxx.h:3078:60: error: class ‘__gmp_expr<__mpf_struct [1], __gmp_urandomb_value>’ does not have any field named ‘bits’
   __gmp_expr(gmp_randstate_t s, mp_bitcnt_t l) : state(s), bits(l) { }
                                                            ^
/usr/include/gmpxx.h: In member function ‘void __gmp_expr<__mpf_struct [1], __gmp_urandomb_value>::eval(mpf_ptr) const’:
/usr/include/gmpxx.h:3082:3: error: ‘bits’ was not declared in this scope
  (bits>0) ? bits : mpf_get_prec(f));
   ^
/usr/include/gmpxx.h: At global scope:
/usr/include/gmpxx.h:3095:90: error: ‘mp_bitcnt_t’ has not been declared
 randinit_lc_2exp_t (gmp_randstate_t, mpz_srcptr, unsigned long int, mp_bitcnt_t
                                                                     ^
/usr/include/gmpxx.h:3096:63: error: ‘mp_bitcnt_t’ has not been declared
   typedef int __gmp_randinit_lc_2exp_size_t (gmp_randstate_t, mp_bitcnt_t);
                                                               ^
/usr/include/gmpxx.h:3125:38: error: ‘mp_bitcnt_t’ has not been declared
   mpz_class z, unsigned long int l1, mp_bitcnt_t l2)
                                      ^
/usr/include/gmpxx.h:3130:3: error: ‘mp_bitcnt_t’ has not been declared
   mp_bitcnt_t size)
   ^
/usr/include/gmpxx.h:3144:54: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr<mpz_t, __gmp_urandomb_value> get_z_bits(mp_bitcnt_t l)
                                                      ^
/usr/include/gmpxx.h:3153:49: error: ‘mp_bitcnt_t’ has not been declared
   __gmp_expr<mpf_t, __gmp_urandomb_value> get_f(mp_bitcnt_t prec = 0)
                                                 ^
Makefile:54: recipe for target '/tmp/libSU3/src/isoscalars.o' failed
make: *** [/tmp/libSU3/src/isoscalars.o] Error 1
`

**Comment by psi-squared** [comment]
I'm going to close this so that there's just one thread for build issues - please see https://github.com/psi-squared/libSU3/issues/2
