### ISSUE TITLE
collect2: error

### ISSUE THREAD

**Issue by natanael87** [psi-squared/libSU3#3]
I tried to compile the ofiles:
`g++ -o csu3 cgarray.o isoarray.o misc.o shw.o su2.o coeff.o isoscalars.o reps.o sqrat.o -lgmpxx -lgmp
`
but it showed this error message:
`/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status`

Can you help me please?

**Comment by psi-squared** [comment]
I'm going to close this so that there's just one thread for build issues - please see https://github.com/psi-squared/libSU3/issues/2
